name: Sync + Rewrite Firefly

on:
  schedule:
    - cron: "0 3 * * *"   # every night at 03:00 UTC
  workflow_dispatch:        # allow manual runs

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout upstream Firefly
        run: |
          git clone https://github.com/firefly-iii/firefly-iii.git upstream
          cd upstream
          git remote add fork https://github.com/${{ github.repository }}.git

      - name: Rewrite CHANGELOG
        run: |
            cd upstream
            # Replace X.Y.Z → version-X.Y.Z in changelog.md
            sed -i -E 's/^## ([0-9]+\.[0-9]+\.[0-9]+)/## version-\1/g' changelog.md
            git config user.name "Mirror Bot"
            git config user.email "bot@example.com"
            git add changelog.md
            git commit -m "Rewrite changelog for Renovate" || echo "No changes"
            git push fork HEAD:main